import Navigation from "./navigation";
import Head from "next/head";
import Theme from "./theme";
import Footer from "./footer";

const Layout = ({children}) => {


    return (
        <Theme>
        <div className={'mx-auto max-w-screen-desktop py-2'}>
            <Head>
                <title>Firebase-App-Tailwind</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <Navigation/>
            {children}
            <Footer />
        </div>
        </Theme>
    )
}

export default Layout